name: CI-tes
on:
  push
jobs:
  build:

    env:
      PY_COLORS: "1"
      GLOBAL_PROXY: ${{ secrets.GLOBAL_PROXY }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python 
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: run tests
      run: python codefresh.py 
    - name: Checkout
      uses: actions/checkout@v4

